backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  #yaml middleman data example

  - name: users
    label: Users
    format: yml
    extension: yml
    folder: data/users/
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Image, name: image, widget: image, required: true}